const BOX_PADDING_SIZE = 0.75;
const LEVELS_PADDING_SIZE = 0.75;
const LAYER_DEFAULT_HEIGTH = 0.25;


exports.BOX_PADDING_SIZE=BOX_PADDING_SIZE;
exports.LEVELS_PADDING_SIZE=LEVELS_PADDING_SIZE;
exports.LAYER_DEFAULT_HEIGTH=LAYER_DEFAULT_HEIGTH;